import random
import matplotlib.pyplot as plt
import networkx as nx
import logging
import time

logging.basicConfig(
    level=logging.INFO,  # Change to DEBUG for more detailed logs
    format='%(asctime)s [%(levelname)s] %(message)s',
    handlers=[
        logging.FileHandler("abc_graph_coloring.log"),
        logging.StreamHandler()
    ]
)


def generate_random_graph(n_vertices=300,
                          min_degree=1,
                          max_degree=30,
                          extra_edges=2000):

    G = nx.Graph()
    G.add_nodes_from(range(n_vertices))

    # Make a simple chain: edges like (0,1), (1,2), ..., (n_vertices-2, n_vertices-1).
    for i in range(n_vertices - 1):
        G.add_edge(i, i + 1)

    # The chain ensures each node has at least degree=1, fulfilling min_degree=1.
    # Now let's add random edges without exceeding max_degree.
    degrees = dict(G.degree())

    attempts = 0
    while attempts < extra_edges:
        u, v = random.sample(range(n_vertices), 2)
        if not G.has_edge(u, v):
            # Only add if both nodes are below max_degree
            if degrees[u] < max_degree and degrees[v] < max_degree:
                G.add_edge(u, v)
                degrees[u] += 1
                degrees[v] += 1
        attempts += 1

    # Convert the resulting NetworkX Graph to an adjacency list
    adjacency_list = {node: sorted(list(G.neighbors(node))) for node in G.nodes()}
    return adjacency_list


def calculate_conflicts(solution, adjacency_list):
    conflict_count = 0
    for v in adjacency_list:
        for nbr in adjacency_list[v]:
            if v < nbr and solution[v] == solution[nbr]:
                conflict_count += 1
    return conflict_count


def generate_initial_solutions(num_solutions, num_vertices, max_colors=10):
    logging.info("Generating %d initial solutions with %d colors.", num_solutions, max_colors)
    solutions = []
    for _ in range(num_solutions):
        solution = [random.randint(0, max_colors - 1) for _ in range(num_vertices)]
        solutions.append(solution)
    logging.debug("Initial solutions generated.")
    return solutions


def neighbor_solution(solution, max_colors=10):
    new_sol = solution[:]
    index_to_modify = random.randint(0, len(new_sol) - 1)
    current_color = new_sol[index_to_modify]
    new_color = random.randint(0, max_colors - 1)

    # Ensure a different color
    attempts = 0
    while new_color == current_color and attempts < 5:
        new_color = random.randint(0, max_colors - 1)
        attempts += 1

    new_sol[index_to_modify] = new_color
    logging.debug("Neighbor solution generated by changing vertex %d from color %d to %d.",
                  index_to_modify, current_color, new_color)
    return new_sol


def employed_bee_phase(solutions, fitnesses, adjacency_list, max_colors=10):
    logging.debug("Starting Employed Bee Phase.")
    for i in range(len(solutions)):
        candidate = neighbor_solution(solutions[i], max_colors)
        candidate_conflicts = calculate_conflicts(candidate, adjacency_list)
        if candidate_conflicts < fitnesses[i]:
            solutions[i] = candidate
            fitnesses[i] = candidate_conflicts
            logging.debug("Employed Bee improved solution %d to %d conflicts.", i, candidate_conflicts)
    logging.debug("Employed Bee Phase completed.")
    return solutions, fitnesses


def onlooker_bee_phase(solutions, fitnesses, adjacency_list, max_colors=10):
    logging.debug("Starting Onlooker Bee Phase.")
    # Compute probabilities: probability ~ 1 / (1 + conflicts)
    total_fitness = sum([1.0 / (1 + f) for f in fitnesses])
    if total_fitness == 0:
        probabilities = [1.0 / len(fitnesses)] * len(fitnesses)
    else:
        probabilities = [(1.0 / (1 + f)) / total_fitness for f in fitnesses]

    num_onlookers = len(solutions)
    for _ in range(num_onlookers):
        r = random.random()
        cumulative = 0.0
        selected_index = None
        for i, prob in enumerate(probabilities):
            cumulative += prob
            if r <= cumulative:
                selected_index = i
                break
        if selected_index is not None:
            candidate = neighbor_solution(solutions[selected_index], max_colors)
            candidate_conflicts = calculate_conflicts(candidate, adjacency_list)
            if candidate_conflicts < fitnesses[selected_index]:
                solutions[selected_index] = candidate
                fitnesses[selected_index] = candidate_conflicts
                logging.debug("Onlooker Bee improved solution %d to %d conflicts.",
                              selected_index, candidate_conflicts)
    logging.debug("Onlooker Bee Phase completed.")
    return solutions, fitnesses


def scout_bee_phase(solutions, fitnesses, adjacency_list, num_scouts=5, max_colors=10):
    logging.debug("Starting Scout Bee Phase.")
    worst_indices = sorted(range(len(solutions)),
                           key=lambda i: fitnesses[i],
                           reverse=True)[:num_scouts]

    for i in worst_indices:
        old_conflicts = fitnesses[i]
        new_solution = [random.randint(0, max_colors - 1)
                        for _ in range(len(solutions[i]))]
        new_conflicts = calculate_conflicts(new_solution, adjacency_list)
        solutions[i] = new_solution
        fitnesses[i] = new_conflicts
        logging.debug("Scout Bee replaced solution %d from %d to %d conflicts.",
                      i, old_conflicts, new_conflicts)
    logging.debug("Scout Bee Phase completed.")
    return solutions, fitnesses


def abc_algorithm(adjacency_list, max_iterations=1000,
                  total_bees=60, scout_bees=5, max_colors=10):
    logging.info("Starting ABC Algorithm: max_iterations=%d, total_bees=%d, scout_bees=%d, max_colors=%d",
                 max_iterations, total_bees, scout_bees, max_colors)

    # Split bees among employed, onlooker, and scout
    employed_bees = (total_bees - scout_bees) // 2
    onlooker_bees = total_bees - employed_bees - scout_bees
    logging.info("Bee distribution -> Employed: %d, Onlooker: %d, Scout: %d",
                 employed_bees, onlooker_bees, scout_bees)

    # Generate initial solutions
    num_vertices = len(adjacency_list)  # Each key in adjacency_list is a node
    solutions = generate_initial_solutions(total_bees, num_vertices, max_colors)
    fitnesses = [calculate_conflicts(sol, adjacency_list) for sol in solutions]

    best_conflicts_evolution = []
    best_solution = None
    best_conflicts = float('inf')

    start_time = time.time()

    for iteration in range(1, max_iterations + 1):
        iteration_start_time = time.time()

        # Employed Bee Phase
        solutions, fitnesses = employed_bee_phase(solutions, fitnesses, adjacency_list, max_colors)

        # Onlooker Bee Phase
        solutions, fitnesses = onlooker_bee_phase(solutions, fitnesses, adjacency_list, max_colors)

        # Scout Bee Phase
        solutions, fitnesses = scout_bee_phase(solutions, fitnesses, adjacency_list,
                                               num_scouts=scout_bees,
                                               max_colors=max_colors)

        # Track the best solution so far
        current_best = min(fitnesses)
        if current_best < best_conflicts:
            best_conflicts = current_best
            best_solution = solutions[fitnesses.index(best_conflicts)]
            logging.info("Iteration %d: New best conflicts found: %d", iteration, best_conflicts)

        # Record performance every 20 iterations
        if iteration % 20 == 0:
            best_conflicts_evolution.append((iteration, best_conflicts))
            logging.info("Iteration %d: Best Conflicts = %d", iteration, best_conflicts)

        # Optional: stop early if a perfect solution is found
        if best_conflicts == 0:
            logging.info("Perfect solution found at iteration %d", iteration)
            break

        iteration_end_time = time.time()
        logging.debug("Iteration %d completed in %.2f seconds.", iteration, iteration_end_time - iteration_start_time)

    end_time = time.time()
    logging.info("ABC Algorithm completed in %.2f seconds.", end_time - start_time)
    logging.info("Best conflicts found: %d", best_conflicts)

    return best_solution, best_conflicts_evolution


def visualize_graph_solution(adjacency_list, solution):
    logging.info("Visualizing the graph with color assignments.")
    G = nx.Graph()

    # Rebuild the graph from adjacency_list
    for v in adjacency_list:
        G.add_node(v)
        for nbr in adjacency_list[v]:
            if v < nbr:
                G.add_edge(v, nbr)

    unique_colors = list(set(solution))
    color_map_dict = {col: idx for idx, col in enumerate(unique_colors)}
    node_colors = [color_map_dict[c] for c in solution]

    # Separate edges into conflicting vs. non-conflicting
    edges = list(G.edges())
    conflicting_edges = []
    non_conflicting_edges = []
    for (v1, v2) in edges:
        if solution[v1] == solution[v2]:
            conflicting_edges.append((v1, v2))
        else:
            non_conflicting_edges.append((v1, v2))

    pos = nx.spring_layout(G, seed=42)

    cmap = plt.get_cmap('rainbow')

    plt.figure(figsize=(12, 8))

    nx.draw_networkx_nodes(
        G, pos,
        node_color=node_colors,
        node_size=50,
        cmap=cmap
    )
    # Draw edges in two batches
    nx.draw_networkx_edges(
        G, pos,
        edgelist=non_conflicting_edges,
        edge_color='black',
        alpha=0.5
    )
    nx.draw_networkx_edges(
        G, pos,
        edgelist=conflicting_edges,
        edge_color='red',
        alpha=0.8
    )

    plt.title("ABC Graph Coloring")
    plt.axis('off')
    plt.show()
    logging.info("Graph visualization completed.")


def plot_performance_evolution(performance_data):
    if not performance_data:
        logging.warning("No performance data to plot.")
        return

    logging.info("Plotting performance evolution.")
    iterations, conflicts = zip(*performance_data)
    plt.figure(figsize=(10, 6))
    plt.plot(iterations, conflicts, marker='o', linestyle='-', color='b')
    plt.xlabel("Iteration")
    plt.ylabel("Best Conflict Count")
    plt.title("Conflict Reduction Over Iterations (ABC)")
    plt.grid(True)
    plt.show()
    logging.info("Performance evolution plot completed.")


def get_user_input_iterations():
    while True:
        try:
            user_input = input("Enter the number of iterations (positive integer): ")
            iterations = int(user_input)
            if iterations <= 0:
                print("Please enter a positive integer greater than 0.")
                continue
            return iterations
        except ValueError:
            print("Invalid input. Please enter a valid positive integer.")


def main():
    random.seed(42)

    max_iterations = get_user_input_iterations()

    # Generate the random connected graph with min_degree=1, max_degree=30
    # The 'extra_edges' can be tweaked to control average density.
    adjacency_list = generate_random_graph(
        n_vertices=300,
        min_degree=1,
        max_degree=30,
        extra_edges=2000
    )

    # Run the ABC algorithm
    best_solution, best_conflicts_evolution = abc_algorithm(
        adjacency_list=adjacency_list,
        max_iterations=max_iterations,
        total_bees=60,
        scout_bees=5,
        max_colors=10
    )

    final_conflicts = calculate_conflicts(best_solution, adjacency_list)
    logging.info("Final Best Solution Conflicts: %d", final_conflicts)
    print(f"\nBest Solution Conflicts: {final_conflicts}")

    visualize_graph_solution(adjacency_list, best_solution)

    plot_performance_evolution(best_conflicts_evolution)


if __name__ == "__main__":
    main()
